project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "Julie Gan"
  repo-url: https://github.com/moricandia/jshgan
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Home (Fun)"
        href: Plantopia.qmd
      - text: "Publications"
        href: Publications.qmd
    right: 
      - icon: github
        href: https://github.com/moricandia/jshgan
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=KSmzX-IAAAAJ&hl=en&oi=ao
  page-footer: 
    center: "Copyright 2025, Julie Gan"
    background: secondary

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false