---
title: "Publications"
format: html
---

Fan, Y., Noble, D. W. A., Medlyn, B. E., Monson, R. K., Sage, R. F., Smith, N. G., Ainsworth, E. A., Busch, F. A., Danila, F. R., Ermakova, M., Friesen, P., Furbank, R. T., **Gan, S. H.**, Ghannoum, O., Griffith, D. M., Gu, L., Jacob, V., Knauer, J., Leakey, A. D. B., … Way, D. A. (2025). Environmental factors have a greater influence on photosynthetic capacity in C4 plants than biochemical subtypes or growth forms. *New Phytologist*, *248*(3), 1205–1224. <https://doi.org/10.1111/nph.70525>

Cooley, S. S., Pinto, N., Becerra, M., Alvarado, J. W. V., Fahlen, J. C., Rivera, O., Fricker, G. A., Dantas, A. R. D. L. R., Aguilar-Amuchastegui, N., Reygadas, Y., **Gan, J.**, DeFries, R., & Menge, D. N. L. (2024). Combining spaceborne lidar from the Global Ecosystem Dynamics Investigation with local knowledge for monitoring fragmented tropical landscapes: A case study in the forest–agriculture interface of Ucayali, Peru. *Ecology and Evolution*, *14*(8), e70116. <https://doi.org/10.1002/ece3.70116>

**Gan, S. H.**, & Sage, R. F. (2024). Stomatal response to VPD in C4 plants with different biochemical sub-pathways. *Plant, Cell & Environment*, *47*(9), 3466–3477. <https://doi.org/10.1111/pce.14952>

**Gan, S. H.**, McTavish, M. J., Bourchier, R. S., & Smith, S. M. (2023). Soil grit influences the effects of earthworms (*Lumbricus terrestris*) on seed damage. *Applied Soil Ecology*, *185*, 104807. <https://doi.org/10.1016/j.apsoil.2023.104807>
